[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["aleksander <aleksander.zdunek@intinor.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
image = "0.13.0"
